name: Create Temporary RDP Server

on:
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Run RDP Server in Docker
      run: |
        # Pull and run a lightweight Ubuntu Docker container with RDP
        docker run -d --name rdp-server -p 3389:3389 danielguerra/ubuntu-xrdp

    - name: Generate RDP Credentials
      id: creds
      run: |
        # Generate a random username and password
        USERNAME=rdpuser
        PASSWORD=$(openssl rand -base64 12)

        # Display the credentials
        echo "USERNAME=${USERNAME}" >> $GITHUB_ENV
        echo "PASSWORD=${PASSWORD}" >> $GITHUB_ENV

    - name: Output RDP Information
      run: |
        echo "Your RDP server is running temporarily on this machine."
        echo "Use the following credentials to connect:"
        echo "Username: $USERNAME"
        echo "Password: $PASSWORD"
        echo "Address: $(curl -s ifconfig.me):3389"
